#!c:\xampp\php\php.exe
<?php
require_once './vendor/autoload.php';

use Taro\Libs\Application;
use Taro\Libs\IOInterface\IOStream;


$stream = new IOStream;

$app = new Application($stream, $argv);

$app->loadConfigData(DS . 'config' . DS .'console.php');
$app->run();